# Generated by Django 5.0.6 on 2024-11-24 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgecomponent',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
