# Generated by Django 5.0.6 on 2024-11-25 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_alter_knowledgecomponent_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influence_probability', models.FloatField()),
                ('dependent_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='influences', to='knowledge.knowledgenode')),
                ('main_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='knowledge.knowledgenode')),
            ],
        ),
    ]
