# Generated by Django 5.0.6 on 2024-11-25 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0003_dependency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WordMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surface_form', models.CharField(max_length=255)),
                ('lemma', models.CharField(max_length=255)),
                ('knowledge_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='knowledge.knowledgecomponent')),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_mappings', to='knowledge.text')),
            ],
        ),
    ]
