# Generated by Django 5.0.6 on 2024-11-25 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0004_text_wordmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='text',
            name='unit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
