# Generated by Django 5.0.6 on 2024-11-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0005_text_grade_text_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glossary',
            name='node',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='node',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
