# Generated by Django 5.0.6 on 2024-11-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_alter_glossary_id_alter_question_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='node',
            field=models.CharField(max_length=255),
        ),
    ]
